#!/bin/bash
#
# Local Development Environment Startup Script
#
# This script port-forwards Kubernetes services to localhost so you can
# run backend Node.js services locally with hot-reload while using
# the actual testnet/mainnet database and Redis.
#
# Usage:
#   ./scripts/dev-local-start.sh              # Use testnet (default)
#   ./scripts/dev-local-start.sh --mainnet    # Use mainnet
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Parse arguments
USE_MAINNET=false
for arg in "$@"; do
    case $arg in
        --mainnet)
            USE_MAINNET=true
            shift
            ;;
    esac
done

# Set namespace based on environment
if [ "$USE_MAINNET" = true ]; then
    BACKEND_NS="backend-mainnet"
    FABRIC_NS="fabric"
    ENV_NAME="MAINNET"
    DB_PASSWORD='IpBZ31PZvN1ma/Q8BIoEhp6haKYRLlUkRk1eRRhtssY='
else
    BACKEND_NS="backend-testnet"
    FABRIC_NS="fabric-testnet"
    ENV_NAME="TESTNET"
    DB_PASSWORD='TESTNET_PASSWORD_HERE'  # Update with actual testnet password
fi

# PID file for cleanup
PID_FILE="/tmp/gx-dev-local.pids"

cleanup() {
    log_info "Stopping port-forwards..."
    if [ -f "$PID_FILE" ]; then
        while read -r pid; do
            kill "$pid" 2>/dev/null || true
        done < "$PID_FILE"
        rm -f "$PID_FILE"
    fi
    pkill -f "kubectl port-forward.*$BACKEND_NS" 2>/dev/null || true
}

trap cleanup EXIT INT TERM

# Clear previous PIDs
rm -f "$PID_FILE"

echo ""
echo "============================================"
echo "  GX Protocol - Local Development"
echo "  Environment: $ENV_NAME"
echo "============================================"
echo ""

# Kill any existing port-forwards
log_info "Cleaning up existing port-forwards..."
pkill -f "kubectl port-forward.*$BACKEND_NS" 2>/dev/null || true
sleep 1

# ============================================
# Port-forward PostgreSQL
# ============================================
log_info "Port-forwarding PostgreSQL (5432)..."
kubectl port-forward -n "$BACKEND_NS" svc/postgres-primary 5432:5432 > /dev/null 2>&1 &
echo $! >> "$PID_FILE"
sleep 2

# Verify PostgreSQL connection
if nc -z localhost 5432 2>/dev/null; then
    log_success "PostgreSQL: localhost:5432"
else
    log_error "PostgreSQL port-forward failed!"
    exit 1
fi

# ============================================
# Port-forward Redis
# ============================================
log_info "Port-forwarding Redis (6379)..."
kubectl port-forward -n "$BACKEND_NS" svc/redis-master 6379:6379 > /dev/null 2>&1 &
echo $! >> "$PID_FILE"
sleep 2

if nc -z localhost 6379 2>/dev/null; then
    log_success "Redis: localhost:6379"
else
    log_error "Redis port-forward failed!"
    exit 1
fi

# ============================================
# Port-forward Fabric (if available)
# ============================================
if kubectl get namespace "$FABRIC_NS" > /dev/null 2>&1; then
    log_info "Port-forwarding Fabric peer (7051)..."
    kubectl port-forward -n "$FABRIC_NS" svc/peer0-org1 7051:7051 > /dev/null 2>&1 &
    echo $! >> "$PID_FILE"

    log_info "Port-forwarding Fabric orderer (7050)..."
    kubectl port-forward -n "$FABRIC_NS" svc/orderer0-org0 7050:7050 > /dev/null 2>&1 &
    echo $! >> "$PID_FILE"

    sleep 2
    log_success "Fabric: localhost:7050/7051"
else
    log_warn "Fabric namespace not found - blockchain operations will fail"
fi

# ============================================
# Create/Update .env.local
# ============================================
ENV_FILE="$PROJECT_ROOT/.env.local"

log_info "Creating .env.local..."
cat > "$ENV_FILE" << EOF
# Local Development Environment - $ENV_NAME
# Auto-generated by dev-local-start.sh
# Do not commit this file!

NODE_ENV=development
LOG_LEVEL=debug

# Database (port-forwarded from $BACKEND_NS)
DATABASE_URL="postgresql://gx_admin:${DB_PASSWORD}@localhost:5432/gx_protocol?schema=public"

# Redis (port-forwarded from $BACKEND_NS)
REDIS_URL=redis://localhost:6379

# Fabric Network (port-forwarded)
FABRIC_PEER_ENDPOINT=localhost:7051
FABRIC_ORDERER_ENDPOINT=localhost:7050
FABRIC_CHANNEL_NAME=gxchannel
FABRIC_CHAINCODE_NAME=gxtv3

# JWT Secrets
JWT_SECRET=dev-jwt-secret-min-32-characters-long
JWT_REFRESH_SECRET=dev-refresh-secret-min-32-chars

# Service Ports (for local development)
SVC_IDENTITY_PORT=3001
SVC_TOKENOMICS_PORT=3003
SVC_ADMIN_PORT=3006
SVC_ORGANIZATION_PORT=3004
SVC_LOANPOOL_PORT=3007
SVC_GOVERNANCE_PORT=3008
SVC_TAX_PORT=3009
EOF

log_success ".env.local created"

# ============================================
# Summary
# ============================================
echo ""
echo "============================================"
echo "  Ready for Local Development!"
echo "============================================"
echo ""
echo "  Port-forwards active:"
echo "    • PostgreSQL: localhost:5432 → $BACKEND_NS"
echo "    • Redis:      localhost:6379 → $BACKEND_NS"
echo "    • Fabric:     localhost:7050/7051 → $FABRIC_NS"
echo ""
echo "  Next steps:"
echo ""
echo "    Terminal 2 - Start Backend:"
echo "      cd $PROJECT_ROOT"
echo "      npm run dev"
echo ""
echo "    Terminal 3 - Start Frontend:"
echo "      cd $(dirname "$PROJECT_ROOT")/gx-wallet-frontend"
echo "      # Edit .env.local: NEXT_PUBLIC_IDENTITY_API_URL=http://localhost:3001"
echo "      npm run dev"
echo ""
echo "  Press Ctrl+C to stop all port-forwards"
echo "============================================"
echo ""

# Keep script running to maintain port-forwards
log_info "Port-forwards running... (Ctrl+C to stop)"
wait
